network:
  ethernets :
    ######:             #Tarjeta de Red.
      dhcp4: no
      addresses: [###.###.###.###/##]
      gateway4: ###.###.###.###
      nameservers:
        addresses: [8.8.8.8, 1.1.1.1]
  version: 2